<a href="https://colab.research.google.com/github/LeMikey/SDGP-HelloWorld/blob/main/main_Flood.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Flood Prediction Model**


In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [35]:
# Get the dataset required
dataSet = pd.read_csv('Monthly rainfall & flood.csv')
dataSet

Year  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec  \
0   1981  113  112  172  270  267  281  159  113  290  208  396  120   
1   1982   47   39  251  360  454  573  217  170  146  481  562  110   
2   1983   39   47   81  106  318  218  145  211  310  215  281  425   
3   1984  277  219  375  465  333  265  330   35  250  236  428  198   
4   1985  201  161  282  150  440  572  136  139  205  495  320  346   
5   1986  158  171  171  388  167  155   97  215  423  355  206  181   
6   1987  118   30  135  261  220  173   15  361  225  463  367  139   
7   1988   83  211  313  379  345  306  230  328  390  129  320  176   
8   1989   55   11  129  195  321  393  417  190  253  385  349   99   
9   1990  112  121  269  232  378  241  198   68   77  420  421  200   
10  1991  229   75  186  257  310  405  184  173   98  361  328  158   
11  1992   67   12   29  266  316  248  299  181  306  329  477  115   
12  1993   34   96  172  270  585  511  221   98  140  562  433  321   
13  1994  150  141  135  201  357  114  192  124  217  414  308  172   
14  1995  195   84  131  514  470  394  115  207  189  371  235   76   
15  1996   93  142  122  395   58  260  227  170  426  311  248  140   
16  1997   29   67   90  345  395  180  290  131  446  514  541  277   
17  1998  115  122  126  235  401  247  287  280  308  297  296  409   
18  1999  144  275  226  445  438  286  122  297  227  419  357  217   
19  2000  144  325  260  142  180  307   81  269  320  203  221  253   
20  2001  361  111   94  410  178  144  201   85  315  333  297  313   
21  2002   89  133  194  487  294  207  167  193  113  441  363  271   
22  2003  108   61  324  355  223  118  294  199  249  285  384   80   
23  2004  104  129  186  410  404  230  236  116  408  425  245  265   
24  2005  150  100  272  373  194  223  205  128  252  365  445  179   
25  2006  166  140  318  224  292  255  126  267  191  572  510  190   
26  2007   89   78  123  446  167  212  161  287  359  394  304  229   
27  2008  196  311  426  506  314  268  345  148  101  454  377  191   
28  2009   58   47  357  271  386  326  134  283  278  337  409  325   
29  2010  158   86  145  342  428  281  235  214  186  278  536  386   
30  2011  239  177  193  467   98   32   40  117   25  149  331  172   
31  2012   64  170  204  420  143  257  151  320  348  555  416  327   
32  2013  124  236  300  183  520  463  308  138  406  361  350  134   
33  2014  154   81  112  352  298  458  149  485  421  352  691  418   
34  2015  108  185  203  406  352  357  213  284  466  445  431  291   
35  2016  121  108  153  300  874  210  181  115   83  233  405  152   
36  2017  174   56  250  195  703  285  182  292  645  588  458  286   
37  2018   57  232  213  430  645  457  143  183  289  702  457  161   
38  2019   74  221  146  328  262  425  221  431  700  621  490  255   
39  2020  119   33  101  342  586  318  324  193  715  208  469  277   

    Annual Rainfall  Floods  
0              2501       0  
1              3410       1  
2              2396       0  
3              3411       1  
4              3447       1  
5              2687       0  
6              2507       0  
7              3210       1  
8              2797       0  
9              2737       0  
10             2764       0  
11             2645       0  
12             3443       1  
13             2525       0  
14             2981       1  
15             2592       0  
16             3305       1  
17             3123       1  
18             3453       1  
19             2705       0  
20             2842       0  
21             2952       1  
22             2680       0  
23             3158       1  
24             2886       0  
25             3251       1  
26             2849       0  
27             3637       1  
28             3211       1  
29             3275       1  
30             2040       0  
31             3375       1  
32             3523       0  
33             3971       1  
3

In [36]:
# Seperating the dataset for calculations
monthly_RF = dataSet.iloc[:,1:13]

monthly_F = dataSet.iloc[:, -1]


In [37]:
# Scaling data between 0 - 1
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(monthly_RF).transform(monthly_RF)


array([[0.25301205, 0.32165605, 0.36020151, 0.40196078, 0.25612745,
        0.46025878, 0.35820896, 0.17333333, 0.38405797, 0.13787086,
        0.39175258, 0.1260745 ],
       [0.05421687, 0.08917197, 0.55919395, 0.62254902, 0.48529412,
        1.        , 0.50248756, 0.3       , 0.17536232, 0.61431065,
        0.73402062, 0.0974212 ],
       [0.03012048, 0.11464968, 0.13098237, 0.        , 0.31862745,
        0.34380776, 0.32338308, 0.39111111, 0.41304348, 0.15008726,
        0.15463918, 1.        ],
       [0.74698795, 0.66242038, 0.87153652, 0.87990196, 0.3370098 ,
        0.43068392, 0.78358209, 0.        , 0.32608696, 0.18673647,
        0.45773196, 0.3495702 ],
       [0.51807229, 0.47770701, 0.6372796 , 0.10784314, 0.46813725,
        0.99815157, 0.30099502, 0.23111111, 0.26086957, 0.63874346,
        0.23505155, 0.77363897],
       [0.38855422, 0.50955414, 0.35768262, 0.69117647, 0.13357843,
        0.22735675, 0.2039801 , 0.4       , 0.57681159, 0.39441536,
        0.        ,

In [38]:
# Split the datasets inot train and test 
monthly_RF_train, monthly_RF_test, monthly_F_train, monthly_F_test=train_test_split(monthly_RF, monthly_F, test_size=0.2)


In [39]:
monthly_RF_train.head()

Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
32  124  236  300  183  520  463  308  138  406  361  350  134
27  196  311  426  506  314  268  345  148  101  454  377  191
1    47   39  251  360  454  573  217  170  146  481  562  110
9   112  121  269  232  378  241  198   68   77  420  421  200
35  121  108  153  300  874  210  181  115   83  233  405  152

In [40]:
monthly_F_train.head()

32    0
27    1
1     1
9     0
35    1
Name: Floods, dtype: int64

## Logistic Regression Machine Learning Algorithm

In [41]:
monthly_RF_train_std = minmax.fit_transform(monthly_RF_train)
monthly_RF_test_std = minmax.transform(monthly_RF_test)

lr = LogisticRegression()
lr_clf = lr.fit(monthly_RF_train_std, monthly_F_train)

lr_accuracy = cross_val_score(lr_clf, monthly_RF_train_std, monthly_F_train, cv=3, scoring='accuracy', n_jobs=-1)

lr_accuracy.mean()

0.8757575757575758

In [42]:
monthly_F_predict = lr_clf.predict(monthly_RF_train_std)
print('Flood has been predicted.')
print(monthly_F_predict)

print('Actual chances of flood')
print(monthly_F_train.values)


Flood has been predicted.
[1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0]
Actual chances of flood
[0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0]


In [43]:
print("\naccuracy score: %f"%(accuracy_score(monthly_F_train,monthly_F_predict)*100))
print("recall score: %f"%(recall_score(monthly_F_train,monthly_F_predict)*100))
print("roc score: %f"%(roc_auc_score(monthly_F_train,monthly_F_predict)*100))


accuracy score: 96.875000
recall score: 100.000000
roc score: 96.666667
