<a href="https://colab.research.google.com/github/LeMikey/SDGP-HelloWorld/blob/main/Flood%20Prediction/main_Flood.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Flood Prediction System**


**Imports**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

**Dataset collection**

In [35]:
# Get the dataset required
dataSet = pd.read_csv('Monthly rainfall & flood.csv')
dataSet.head()

Year  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec  \
0  1981  113  112  172  270  267  281  159  113  290  208  396  120   
1  1982   47   39  251  360  454  573  217  170  146  481  562  110   
2  1983   39   47   81  106  318  218  145  211  310  215  281  425   
3  1984  277  219  375  465  333  265  330   35  250  236  428  198   
4  1985  201  161  282  150  440  572  136  139  205  495  320  346   

   Annual Rainfall  Floods  
0             2501       0  
1             3410       1  
2             2396       0  
3             3411       1  
4             3447       1

In [15]:
# Selecting month depending on input

month = input("Enter month: ")

if month == "january":
    monthly_RF = dataSet.iloc[:,1:2]
    monthly_F = dataSet.iloc[:, -1]

elif month == "february":
    monthly_RF = dataSet.iloc[:,2:3]
    monthly_F = dataSet.iloc[:, -1]

elif month == "march":
    monthly_RF = dataSet.iloc[:,3:4]
    monthly_F = dataSet.iloc[:, -1]

elif month == "april":
    monthly_RF = dataSet.iloc[:,4:5]
    monthly_F = dataSet.iloc[:, -1]

elif month == "may":
    monthly_RF = dataSet.iloc[:,5:6]
    monthly_F = dataSet.iloc[:, -1]

elif month == "june":
    monthly_RF = dataSet.iloc[:,6:7]
    monthly_F = dataSet.iloc[:, -1]

elif month == "july":
    monthly_RF = dataSet.iloc[:,7:8]
    monthly_F = dataSet.iloc[:, -1]

elif month == "august":
    monthly_RF = dataSet.iloc[:,8:9]
    monthly_F = dataSet.iloc[:, -1]

elif month == "september": 
    monthly_RF = dataSet.iloc[:,9:10]
    monthly_F = dataSet.iloc[:, -1]

elif month == "october":
    monthly_RF = dataSet.iloc[:,10:11]
    monthly_F = dataSet.iloc[:, -1]

elif month == "november":
    monthly_RF = dataSet.iloc[:,11:12]
    monthly_F = dataSet.iloc[:, -1]

elif month == "december":
    monthly_RF = dataSet.iloc[:,12:13]
    monthly_F = dataSet.iloc[:, -1]
else:
    print ("Incorrect month!")


Enter month: may


In [36]:
# Scaling data between 0 - 1
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(monthly_RF).transform(monthly_RF)


array([[0.25612745],
       [0.48529412],
       [0.31862745],
       [0.3370098 ],
       [0.46813725],
       [0.13357843],
       [0.19852941],
       [0.35171569],
       [0.32230392],
       [0.39215686],
       [0.30882353],
       [0.31617647],
       [0.64583333],
       [0.36642157],
       [0.50490196],
       [0.        ],
       [0.4129902 ],
       [0.42034314],
       [0.46568627],
       [0.1495098 ],
       [0.14705882],
       [0.28921569],
       [0.20220588],
       [0.42401961],
       [0.16666667],
       [0.28676471],
       [0.13357843],
       [0.31372549],
       [0.40196078],
       [0.45343137],
       [0.04901961],
       [0.10416667],
       [0.56617647],
       [0.29411765],
       [0.36029412],
       [1.        ],
       [0.79044118],
       [0.71936275],
       [0.25      ],
       [0.64705882]])

In [37]:
# Split the datasets into train and test 
monthly_RF_train, monthly_RF_test, monthly_F_train, monthly_F_test=train_test_split(monthly_RF, monthly_F, test_size=0.2)


In [31]:
monthly_RF_train.head()

May
20  178
34  352
15   58
25  292
19  180

In [32]:
monthly_RF_test.head()

May
9   378
11  316
4   440
38  262
26  167

In [33]:
monthly_F_train.head()

20    0
34    1
15    0
25    1
19    0
Name: Floods, dtype: int64

In [34]:
monthly_F_test.head()

9     0
11    0
4     1
38    1
26    0
Name: Floods, dtype: int64

## Logistic Regression Machine Learning Algorithm

**Calculations**

In [22]:
#Prediction model
monthly_RF_train_std = minmax.fit_transform(monthly_RF_train)
monthly_RF_test_std = minmax.transform(monthly_RF_test)

lr = LogisticRegression()
lr_clf = lr.fit(monthly_RF_train_std, monthly_F_train)

lr_accuracy = cross_val_score(lr_clf, monthly_RF_train_std, monthly_F_train, cv=3, scoring='accuracy', n_jobs=-1)

lr_accuracy.mean()

0.5939393939393939

**Generate predicted labels**

In [23]:
#Comparing predictions with real life data
monthly_F_predict = lr_clf.predict(monthly_RF_train_std)
print('Flood has been predicted.')
print(monthly_F_predict)

print('Actual chances of flood')
print(monthly_F_train.values)


Flood has been predicted.
[1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Actual chances of flood
[0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1]


**Comparing predicted and actual results**

In [40]:
print("\naccuracy score: %f"%(accuracy_score(monthly_F_train,monthly_F_predict)*100))
print("recall score: %f"%(recall_score(monthly_F_train,monthly_F_predict)*100))
print("roc score: %f"%(roc_auc_score(monthly_F_train,monthly_F_predict)*100))


accuracy score: 46.875000
recall score: 88.235294
roc score: 44.117647


**Final accuracy**

In [41]:
#Seperating the prediction out into three categories, High risk, Medium risk and Low risk
if (accuracy_score(monthly_F_train,monthly_F_predict)*100)>=65:{
    print("High risk of flood in " + month)
}
elif (accuracy_score(monthly_F_train,monthly_F_predict)*100)>=35: {
    print("Medium risk of flood in " + month)
}
else: {
    print("Low risk of flood in " + month)
}

Medium risk of flood in may
